stages:
  - build
  - info

hello-job:
  stage: build
  script:
    - echo "Hello from $GITLAB_USER_LOGIN"

info-job:
  stage: info
  script:
    - echo "User $GITLAB_USER_LOGIN"
    - echo "Branch $CI_COMMIT_BRANCH"
    - echo "Pipeline ID $CI_PIPELINE_ID"